// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSbm0rw1Z03VR3n5t_Rn_h8WqJaZG3Beg',
    appId: '1:979356928920:android:b9f28d0b471e35eb10f9ed',
    messagingSenderId: '979356928920',
    projectId: 'newme-f9c0a',
    databaseURL: 'https://newme-f9c0a-default-rtdb.firebaseio.com',
    storageBucket: 'newme-f9c0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnDghvczynyCDOupOhWWbO00FAvQrdPBU',
    appId: '1:979356928920:ios:d6a4ca478f7a1c2d10f9ed',
    messagingSenderId: '979356928920',
    projectId: 'newme-f9c0a',
    databaseURL: 'https://newme-f9c0a-default-rtdb.firebaseio.com',
    storageBucket: 'newme-f9c0a.appspot.com',
    androidClientId: '979356928920-0iqfq8svgon4oq2uvq65sn8jkbk8tnmp.apps.googleusercontent.com',
    iosClientId: '979356928920-h5c5emco0dcip6efk08va40il7t9j9n1.apps.googleusercontent.com',
    iosBundleId: 'com.example.po',
  );

}